version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container2
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dani@dani.com
      PGADMIN_DEFAULT_PASSWORD: "12345"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
  
  dbMysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./datadir:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 52010:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  local_pgdata:
  pgadmin-data:
  datadir: